dado = input('Digite algo: ')
print(type(dado))
print('É alfanumérico?', dado.isalnum())
print('É alfabético?', dado.isalpha())
print('É decimal?', dado.isdecimal())
print('É um digito?', dado.isdigit())
print('É um identificador?', dado.isidentifier())
print('É um número?', dado.isnumeric())
print('É imprimível?', dado.isprintable())
print('É um espaço?', dado.isspace())
print('É um título?', dado.istitle())
print('É um maiúsculo?', dado.isupper())
print('É um minúsculo?', dado.islower())
print('É um capitalizado?', dado.istitle())
